version: "3"

services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      LEVEL_NAME: "BedrockWorld"
      SERVER_NAME: "HexagonalServer"
      MAX_PLAYERS: "10"
    volumes:
      - ./bedrock-data:/data
    restart: unless-stopped